title: Christian Schweizer # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Software Engineer at Swiss International Airlines
  <br><br>
  MSc Business Administration Information and Data Management, FHGR, 2020
  <br><br>
  BSc Information Science, ZHAW, 2013
  <br><br>
  ZÃ¼rich, Switzerland 
  <br><br>
  <a href="https://www.linkedin.com/in/christian-schweizer-527025a5/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
